### ISSUE TITLE
Since 7.1.2 `shell: false` commands with any argument fails with "undefined local variable or method `default_args' "

### ISSUE THREAD

**Issue by zaratan** [bibendi/dip#135]
**Describe the bug**
Since 7.1.2 (It works with 7.1.1) if a command is declared as `shell: false` it will fail if given any argument.

Here is the stacktrace:
```
Traceback (most recent call last):
        9: from /Users/pasind/.rvm/gems/ruby-2.7.4@shotgun/gems/dip-7.1.2/exe/dip:23:in `<main>'
        8: from /Users/pasind/.rvm/gems/ruby-2.7.4@shotgun/gems/dip-7.1.2/lib/dip/cli.rb:31:in `start'
        7: from /Users/pasind/.rvm/gems/ruby-2.7.4@shotgun/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        6: from /Users/pasind/.rvm/gems/ruby-2.7.4@shotgun/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        5: from /Users/pasind/.rvm/gems/ruby-2.7.4@shotgun/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        4: from /Users/pasind/.rvm/gems/ruby-2.7.4@shotgun/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        3: from /Users/pasind/.rvm/gems/ruby-2.7.4@shotgun/gems/dip-7.1.2/lib/dip/cli.rb:85:in `run'
        2: from /Users/pasind/.rvm/gems/ruby-2.7.4@shotgun/gems/dip-7.1.2/lib/dip/commands/run.rb:30:in `execute'
        1: from /Users/pasind/.rvm/gems/ruby-2.7.4@shotgun/gems/dip-7.1.2/lib/dip/commands/run.rb:59:in `compose_arguments'
/Users/pasind/.rvm/gems/ruby-2.7.4@shotgun/gems/dip-7.1.2/lib/dip/commands/run.rb:84:in `get_args': undefined local variable or method `default_args' for #<Dip::Commands::Run:0x00007f939d82d628> (NameError)
```

**To Reproduce**
1. Provide dip.yml config
```yml
compose:
  files:
    - ./docker-compose.yml
interaction:
  rvm:
    description: Start rvm in the app container
    service: app_dev
    command: rvm
    shell: false
```

2. Provide docker-compose.yml
Not really relevant. I can provide one if needed.

3. Run command
`dip rvm install 2.7.4`

**Expected behavior**
Should work.

**Screenshots**
<img width="1459" alt="Capture d’écran 2021-07-14 à 09 45 51" src="https://user-images.githubusercontent.com/3338913/125544195-8e11602e-8495-46b6-84a5-5d7b854b8407.png">
The second `dip` command is using `7.1.1`

**Context (please complete the following information):**
 - OS: OSX 14
 - Version 7.1.2

**Comment by zaratan** [comment]
I know what the problem is and how to fix it. I'll open a PR soon. I wanted to have a corresponding issue to document the problem.

**Comment by zaratan** [comment]
This commit is the culprit: https://github.com/bibendi/dip/commit/7d2c3525f46fd9b9dcac0190e84480bc8f0d471b
